### ISSUE TITLE
Selling

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [lenzh/Lenzh_chopshop#1]
I installed everything and chop a vehicle and it works. Got all the parts. Then when i go to sell no notification pop no menu no marke so i made one and it show but still wont get a menu to sell. Not sure if i am the only one. Just thought i would tell you. I will check if i can fix it.

**Comment by wowpanda** [comment]
I see in code this using pNotify

**Comment by XxFri3ndlyxX** [comment]
Yes i do have this but it has nothing to do with pnotify. The string is not working for selling menu. The selling menu is broken or something.  The string works fine for chopping.

**Comment by XxFri3ndlyxX** [comment]
All good now i fixed it. IT works now.
<a href="https://imgur.com/NdVN51i"><img src="https://i.imgur.com/NdVN51i.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/0Jaa1ve"><img src="https://i.imgur.com/0Jaa1ve.jpg" title="source: imgur.com" /></a>

**Comment by vikista** [comment]
How did you fix it ?

**Comment by XxFri3ndlyxX** [comment]
This ticket was closed.... Just use recent version....
