### ISSUE TITLE
when choping cars you can drive

### ISSUE THREAD

**Issue by x20i** [lenzh/Lenzh_chopshop#19]
when you are chopping a car you can still drive than when it is done the car will delete fix is to set car undrivable when chopping

-- 0x8ABA6AF54B942B95 0x48D02A4E
-- SET_VEHICLE_UNDRIVEABLE
SetVehicleUndriveable(vehicle --[[ Vehicle ]],  toggle --[[ boolean ]])

**Comment by lenzh** [comment]
Already in there

**Comment by x20i** [comment]
https://gyazo.com/c5fe04246d1de695fb8a810c6c9ad7eb
https://gyazo.com/3fceb182ec089b41478edf29d85e6fb4

**Comment by lenzh** [comment]
U edited my resource and u probably fucked up.. download the latest one

**Comment by x20i** [comment]
lol just bc I change a pos don't fuck up a code you put it in the config for a reason to make it easy to change right lol so take the dick out your ass

**Comment by lenzh** [comment]
well fuck off out of my git then ;)
