### ISSUE TITLE
Could not start resource

### ISSUE THREAD

**Issue by BryBTG** [lenzh/Lenzh_chopshop#20]
I dont know why that shows on my cmd

**Comment by lenzh** [comment]
Make sure its start Lenzh_chopshop

**Comment by BryBTG** [comment]
https://imgur.com/a/ZAvKCxf I did everything fine but still cant load the resource.

**Comment by lenzh** [comment]
U dont have progressBars

**Comment by BryBTG** [comment]
I do have progressbars

**Comment by lenzh** [comment]
Then go in __resource and remove all dependency shit
