### ISSUE TITLE
Cannot load esx_inventoryhud after adding assets to __resource.lua

### ISSUE THREAD

**Issue by snow-desuri** [lenzh/Lenzh_chopshop#21]
So after moving the image files to the correct location and adding those to the __resource.lua of esx_inventoryhud, the server is telling me that it cannot load the resource esx_inventoryhud. If I remove the images from the __resource.lua each works wonderfully. I've checked for spelling mismatches, any anything that might be different for these. 

The Console is telling me that the code after that first line adding these images is no longer closed by } when it is. 

  "html/img/items/battery.png",
  "html/img/items/lowradio.png",
  "html/img/items/stockrim.png",
  "html/img/items/airbag.png",
  "html/img/items/highradio.png",
  "html/img/items/highrim.png",
}

Pulled straight from the script. Battery.png is on line 125 of the lua file, and the console say's that's where it's expecting the closed }. 

Any idea's?

**Comment by lenzh** [comment]
U forgot a , on the resource lua not on my files but inventoryhud defaults
