### ISSUE TITLE
Error when ' if xPlayer.getInventoryItem(v).count >= xPlayer.getInventoryItem(v).limit then'

### ISSUE THREAD

**Issue by TK997** [lenzh/Lenzh_chopshop#24]
When comparing if the count of particular item is bigger or equal to limit of that item, I get

> SCRIPT ERROR: @Lenzh_chopshop/server/main.lua:36: attempt to compare nil with number

I think the problem is that it doesn't fetch back the value of limit :/

EDIT: The whole script it's outdated and will not work on weight system, not sure it worked on the limit system as well :/ I mean... chopshop.sql inserts data into 'items' table, but getInventoryItem().limit it's defined as fetching data from user_inventory... so please comment this one too Lenzh :)
btw: no offense meant. I love your work <3

**Comment by lenzh** [comment]
I havent worked on this script in ages and will probably not do anymore. So if you feel like to change it go ahead. Maaybee if i have the time ill look into it but for now i wont.
