### ISSUE TITLE
Selling

### ISSUE THREAD

**Issue by Chip-W** [lenzh/Lenzh_chopshop#8]
I have an issue when I sell to Stanley once, I can never sell to him again unless I restart the resource.  Once it's been restarted, I can only sell to him once.  I've waited up to an hour between selling and trying to sell again.

**Comment by XxFri3ndlyxX** [comment]
Try my version and see if everything works 
https://github.com/XxFri3ndlyxX/Lenzh_chopshop
For some reason something fucked up somehow in his version.  Not sure what happen.

**Comment by Chip-W** [comment]
Nope.  With yours, there was no cooldown on chopping, but still didn't sell second time around.

**Comment by XxFri3ndlyxX** [comment]
Well it's weird you must have something conflicting with it then. I tested it on 3 different server. 2 fresh test server  and my server.
I literally just made a new server just to test is and it works.

**Comment by XxFri3ndlyxX** [comment]
Check your logs in fivem app-data for errors. Also you need pnotify and needs to start before this script and this script needs to start after all jobs

**Comment by Chip-W** [comment]
yup, that is how it's setup.  Currently, I don't have very many scripts (considering it is ESX).  It's a new server build.  I'm using your version without any edits.

**Comment by XxFri3ndlyxX** [comment]
Well it is very weird that its not working for you. I will recheck the code tomorrow. Right now i'm heading to bed.

**Comment by Chip-W** [comment]
I am here in a minute myself after I test one more thing.  I did go in and comment out any esx script that wasn't downloaded from esx-org just for giggles to no avail.  The only other thing I'm going to try before giving up is updating essentialmode.  If that's the issue, then I guess I can't use this chop shop because es 6 seems to break rcon commands and I need those for my CAD.

**Comment by Chip-W** [comment]
FINALLY!!!  I sort of found my problem, now to figure out why it happens.  My issue is walking away without closing the menu and letting it just close on it own.  If I close the menu then walk away, I get the option to open it again.

**Comment by XxFri3ndlyxX** [comment]
Great !!! then this will be easy to fix. I will work on it tomorrow.

**Comment by Chip-W** [comment]
Ok, client/main.lua

I commented out lines 68 (menuOpen = true) and line 96 (menuOpen = false).  This fixed the issue with just walking away from the marker to close the menu and then not having it open back up for me.  Basically, it was stuck open even though the menu disappeared.

Thanks for helping.  Have a good night.  Also, I'm in Ark's discord as well, just seen you were in there.
